// Estructura para clases (completado con todos los cooldowns)
const WOW_CLASSES = {
 PRIEST: {
    color: '#FFFFFF',
    icon: '✝️',
    HOLY: [
      { name: 'Divine Hymn', icon: '🧿', type: 'healing', duration: 8, cooldown: 180, description: 'Raid healing, 40% increased healing' },
      { name: 'Guardian Spirit', icon: '🕊️', type: 'defensive', duration: 10, cooldown: 180, description: 'Prevents death, 60% increased healing' },
      { name: 'Holy Word: Salvation', icon: '🌟', type: 'healing', duration: 'Instant', cooldown: 300, description: 'Raid-wide heal and HoT' },
      { name: 'Symbol of Hope', icon: '💫', type: 'utility', duration: 4, cooldown: 180, description: 'Restores mana to healers' },
      { name: 'Apotheosis', icon: '👑', type: 'healing', duration: 20, cooldown: 120, description: 'Reduces Holy Word cooldowns' },
      { name: 'Desperate Prayer', icon: '🙏', type: 'defensive', duration: 'Instant', cooldown: 90, description: 'Increases max health by 25% and heals for that amount' },
      { name: 'Leap of Faith', icon: '👐', type: 'utility', duration: 'Instant', cooldown: 90, description: 'Pulls ally to priest, removing movement impairing effects' },
    ],
    DISCIPLINE: [
      { name: 'Power Word: Barrier', icon: '🛡️', type: 'defensive', duration: 10, cooldown: 180, description: 'Reduces damage taken by 25%' },
      { name: 'Pain Suppression', icon: '🔄', type: 'defensive', duration: 8, cooldown: 180, description: 'Reduces damage taken by 40%' },
      { name: 'Rapture', icon: '✨', type: 'healing', duration: 8, cooldown: 90, description: 'Improved shields, no weakened soul' },
      { name: 'Evangelism', icon: '📢', type: 'healing', duration: 'Instant', cooldown: 90, description: 'Extends Atonement durations' },
      { name: 'Spirit Shell', icon: '🐚', type: 'healing', duration: 10, cooldown: 60, description: 'Converts healing to absorbs' },
      { name: 'Desperate Prayer', icon: '🙏', type: 'defensive', duration: 'Instant', cooldown: 90, description: 'Increases max health by 25% and heals for that amount' },
      { name: 'Leap of Faith', icon: '👐', type: 'utility', duration: 'Instant', cooldown: 90, description: 'Pulls ally to priest, removing movement impairing effects' },
      { name: 'Ultimate Penitence', icon: '🔱', type: 'healing', duration: 15, cooldown: 240, description: 'Increases Atonement healing by 100% and adds Atonement to all raid members' },
    ],
    SHADOW: [
      { name: 'Vampiric Embrace', icon: '🧛', type: 'healing', duration: 15, cooldown: 120, description: 'Self healing and ally healing' },
      { name: 'Dispersion', icon: '👻', type: 'defensive', duration: 6, cooldown: 120, description: '75% damage reduction, stun break' },
      { name: 'Void Shift', icon: '🔮', type: 'utility', duration: 'Instant', cooldown: 300, description: 'Swap health percentage with target' },
      { name: 'Desperate Prayer', icon: '🙏', type: 'defensive', duration: 'Instant', cooldown: 90, description: 'Increases max health by 25% and heals for that amount' },
      { name: 'Psychic Horror', icon: '😱', type: 'utility', duration: 4, cooldown: 45, description: 'Stuns target and causes them to flee in horror' },
    ]
  },
  PALADIN: {
    color: '#F58CBA',
    icon: '🔨',
    HOLY: [
      { name: 'Aura Mastery', icon: '🌈', type: 'defensive', duration: 8, cooldown: 180, description: 'Empowers active aura' },
      { name: 'Avenging Wrath', icon: '👼', type: 'healing', duration: 20, cooldown: 120, description: 'Increases healing by 30%' },
      { name: 'Holy Avenger', icon: '⚔️', type: 'healing', duration: 20, cooldown: 180, description: 'Holy Power generators grant 3 HP' },
      { name: 'Beacon of Virtue', icon: '💠', type: 'healing', duration: 8, cooldown: 15, description: 'Multi-target beacon effect' },
      { name: 'Divine Shield', icon: '🛡️', type: 'defensive', duration: 8, cooldown: 300, description: 'Complete immunity to damage' },
      { name: 'Blessing of Protection', icon: '🤲', type: 'defensive', duration: 10, cooldown: 300, description: 'Prevents physical damage' },
      { name: 'Blessing of Sacrifice', icon: '🩸', type: 'defensive', duration: 12, cooldown: 120, description: 'Transfers 30% damage to paladin' },
      { name: 'Lay on Hands', icon: '✋', type: 'healing', duration: 'Instant', cooldown: 600, description: 'Heals target to full health' },
      { name: 'Divine Steed', icon: '🐎', type: 'utility', duration: 3, cooldown: 45, description: 'Increases movement speed by 100%' },
      { name: 'Blessing of Freedom', icon: '🦅', type: 'utility', duration: 8, cooldown: 25, description: 'Removes movement impairing effects' },
    ],
    PROTECTION: [
      { name: 'Guardian of Ancient Kings', icon: '👑', type: 'defensive', duration: 8, cooldown: 300, description: '50% damage reduction' },
      { name: 'Ardent Defender', icon: '🔱', type: 'defensive', duration: 8, cooldown: 120, description: '20% damage reduction, prevents death' },
      { name: 'Divine Shield', icon: '🛡️', type: 'defensive', duration: 8, cooldown: 300, description: 'Complete immunity to damage' },
      { name: 'Blessing of Protection', icon: '🤲', type: 'defensive', duration: 10, cooldown: 300, description: 'Prevents physical damage' },
      { name: 'Blessing of Sacrifice', icon: '🩸', type: 'defensive', duration: 12, cooldown: 120, description: 'Transfers 30% damage to paladin' },
      { name: 'Lay on Hands', icon: '✋', type: 'healing', duration: 'Instant', cooldown: 600, description: 'Heals target to full health' },
      { name: 'Shield of the Righteous', icon: '🔰', type: 'defensive', duration: 4.5, cooldown: 1, description: 'Reduces physical damage taken by 30%' },
      { name: 'Eye of Tyr', icon: '👁️', type: 'defensive', duration: 9, cooldown: 60, description: 'Reduces enemy damage dealt by 25%' },
      { name: 'Divine Steed', icon: '🐎', type: 'utility', duration: 3, cooldown: 45, description: 'Increases movement speed by 100%' },
      { name: 'Blessing of Freedom', icon: '🦅', type: 'utility', duration: 8, cooldown: 25, description: 'Removes movement impairing effects' },
    ],
    RETRIBUTION: [
      { name: 'Divine Shield', icon: '🛡️', type: 'defensive', duration: 8, cooldown: 300, description: 'Complete immunity to damage' },
      { name: 'Blessing of Protection', icon: '🤲', type: 'defensive', duration: 10, cooldown: 300, description: 'Prevents physical damage' },
      { name: 'Blessing of Sacrifice', icon: '🩸', type: 'defensive', duration: 12, cooldown: 120, description: 'Transfers 30% damage to paladin' },
      { name: 'Word of Glory', icon: '✨', type: 'healing', duration: 'Instant', cooldown: 0, description: 'Self or ally heal, costs Holy Power' },
      { name: 'Lay on Hands', icon: '✋', type: 'healing', duration: 'Instant', cooldown: 600, description: 'Heals target to full health' },
      { name: 'Shield of Vengeance', icon: '💥', type: 'defensive', duration: 15, cooldown: 120, description: 'Absorbs damage and deals it back' },
      { name: 'Divine Steed', icon: '🐎', type: 'utility', duration: 3, cooldown: 45, description: 'Increases movement speed by 100%' },
      { name: 'Blessing of Freedom', icon: '🦅', type: 'utility', duration: 8, cooldown: 25, description: 'Removes movement impairing effects' },
    ]
  },
  DRUID: {
    color: '#FF7D0A',
    icon: '🐾',
    RESTORATION: [
      { name: 'Tranquility', icon: '🌀', type: 'healing', duration: 8, cooldown: 180, description: 'Channeled raid healing' },
      { name: 'Incarnation: Tree of Life', icon: '🌳', type: 'healing', duration: 30, cooldown: 180, description: 'Enhanced healing abilities' },
      { name: 'Flourish', icon: '🌸', type: 'healing', duration: 8, cooldown: 90, description: 'Extends HoT durations and increases tick rate' },
      { name: 'Innervate', icon: '🌙', type: 'utility', duration: 10, cooldown: 180, description: 'Free spell casting' },
      { name: 'Ironbark', icon: '🌿', type: 'defensive', duration: 12, cooldown: 90, description: '20% damage reduction' },
      { name: 'Nature\'s Swiftness', icon: '🍃', type: 'utility', duration: 'Instant', cooldown: 60, description: 'Next nature spell is instant' },
      { name: 'Wild Growth', icon: '🌱', type: 'healing', duration: 7, cooldown: 10, description: 'AoE HoT on up to 5 targets' },
      { name: 'Overgrowth', icon: '🍀', type: 'healing', duration: 'Instant', cooldown: 60, description: 'Applies multiple HoTs to target' },
      { name: 'Barkskin', icon: '🌳', type: 'defensive', duration: 12, cooldown: 60, description: '20% damage reduction' },
      { name: 'Stampeding Roar', icon: '🦁', type: 'utility', duration: 8, cooldown: 120, description: 'Increases movement speed of all allies' },
    ],
    BALANCE: [
      { name: 'Innervate', icon: '🌙', type: 'utility', duration: 10, cooldown: 180, description: 'Free spell casting' },
      { name: 'Barkskin', icon: '🌳', type: 'defensive', duration: 12, cooldown: 60, description: '20% damage reduction' },
      { name: 'Nature\'s Vigil', icon: '🌿', type: 'healing', duration: 30, cooldown: 90, description: 'Heals allies for portion of damage' },
      { name: 'Solar Beam', icon: '☀️', type: 'utility', duration: 8, cooldown: 60, description: 'Silences and interrupts in area' },
      { name: 'Starfall', icon: '⭐', type: 'damage', duration: 8, cooldown: 0, description: 'AoE damage over time, costs Astral Power' },
      { name: 'Cyclone', icon: '🌪️', type: 'utility', duration: 6, cooldown: 30, description: 'Incapacitates target and makes them invulnerable' },
      { name: 'Renewal', icon: '💚', type: 'healing', duration: 'Instant', cooldown: 90, description: 'Heals for 30% of maximum health' },
      { name: 'Stampeding Roar', icon: '🦁', type: 'utility', duration: 8, cooldown: 120, description: 'Increases movement speed of all allies' },
    ],
    FERAL: [
      { name: 'Survival Instincts', icon: '🐯', type: 'defensive', duration: 6, cooldown: 180, description: '50% damage reduction' },
      { name: 'Frenzied Regeneration', icon: '🩹', type: 'healing', duration: 3, cooldown: 36, description: 'Self heal based on damage taken' },
      { name: 'Berserk', icon: '😾', type: 'damage', duration: 20, cooldown: 180, description: 'Increases energy regeneration' },
      { name: 'Tiger\'s Fury', icon: '🐅', type: 'damage', duration: 10, cooldown: 30, description: 'Increases damage and generates energy' },
      { name: 'Incapacitating Roar', icon: '😴', type: 'utility', duration: 3, cooldown: 30, description: 'AoE incapacitate' },
      { name: 'Renewal', icon: '💚', type: 'healing', duration: 'Instant', cooldown: 90, description: 'Heals for 30% of maximum health' },
      { name: 'Barkskin', icon: '🌳', type: 'defensive', duration: 12, cooldown: 60, description: '20% damage reduction' },
      { name: 'Stampeding Roar', icon: '🦁', type: 'utility', duration: 8, cooldown: 120, description: 'Increases movement speed of all allies' },
    ],
    GUARDIAN: [
      { name: 'Survival Instincts', icon: '🐻', type: 'defensive', duration: 6, cooldown: 180, description: '50% damage reduction' },
      { name: 'Frenzied Regeneration', icon: '🩹', type: 'healing', duration: 3, cooldown: 36, description: 'Self heal based on damage taken' },
      { name: 'Barkskin', icon: '🌳', type: 'defensive', duration: 12, cooldown: 60, description: '20% damage reduction' },
      { name: 'Bristling Fur', icon: '🦔', type: 'defensive', duration: 8, cooldown: 40, description: 'Rage generation from damage' },
      { name: 'Ironfur', icon: '🧸', type: 'defensive', duration: 7, cooldown: 0, description: 'Increases armor, can stack' },
      { name: 'Berserk', icon: '🐻‍❄️', type: 'defensive', duration: 15, cooldown: 180, description: 'Reduces all ability costs' },
      { name: 'Incapacitating Roar', icon: '😴', type: 'utility', duration: 3, cooldown: 30, description: 'AoE incapacitate' },
      { name: 'Stampeding Roar', icon: '🦁', type: 'utility', duration: 8, cooldown: 120, description: 'Increases movement speed of all allies' },
    ]
  },
  SHAMAN: {
    color: '#0070DE',
    icon: '⚡',
    RESTORATION: [
      { name: 'Healing Tide Totem', icon: '🌊', type: 'healing', duration: 10, cooldown: 180, description: 'AoE healing totem' },
      { name: 'Spirit Link Totem', icon: '⛓️', type: 'defensive', duration: 6, cooldown: 180, description: 'Redistributes health, 10% reduction' },
      { name: 'Ancestral Protection Totem', icon: '🔮', type: 'defensive', duration: 30, cooldown: 300, description: 'Prevents death, revives with 20% health' },
      { name: 'Healing Stream Totem', icon: '💧', type: 'healing', duration: 15, cooldown: 30, description: 'Single-target healing totem' },
      { name: 'Earthen Wall Totem', icon: '🧱', type: 'defensive', duration: 15, cooldown: 60, description: 'Absorbs damage' },
      { name: 'Ascendance', icon: '👼', type: 'healing', duration: 15, cooldown: 180, description: 'All heals echo to nearby allies' },
      { name: 'Wellspring', icon: '🌟', type: 'healing', duration: 'Instant', cooldown: 20, description: 'Cone-based multi-target heal' },
      { name: 'Spirit Walk', icon: '👻', type: 'utility', duration: 8, cooldown: 60, description: 'Removes movement impairing effects' },
      { name: 'Spiritwalker\'s Grace', icon: '👣', type: 'utility', duration: 15, cooldown: 120, description: 'Cast while moving' },
      { name: 'Wind Rush Totem', icon: '💨', type: 'utility', duration: 15, cooldown: 120, description: 'Increases movement speed of allies' },
    ],
    ELEMENTAL: [
      { name: 'Astral Shift', icon: '🌠', type: 'defensive', duration: 8, cooldown: 90, description: '40% damage reduction' },
      { name: 'Earth Elemental', icon: '🗿', type: 'defensive', duration: 60, cooldown: 300, description: 'Summons Earth Elemental tank' },
      { name: 'Thunderstorm', icon: '⚡', type: 'utility', duration: 'Instant', cooldown: 30, description: 'Knocks back enemies, restores mana' },
      { name: 'Wind Shear', icon: '🌬️', type: 'utility', duration: 'Instant', cooldown: 12, description: 'Interrupts spellcasting' },
      { name: 'Capacitor Totem', icon: '⚡', type: 'utility', duration: 'Instant', cooldown: 60, description: 'AoE stun after 2 seconds' },
      { name: 'Tremor Totem', icon: '📳', type: 'utility', duration: 10, cooldown: 60, description: 'Breaks fear, charm, sleep effects' },
      { name: 'Spiritwalker\'s Grace', icon: '👣', type: 'utility', duration: 15, cooldown: 120, description: 'Cast while moving' },
      { name: 'Spirit Walk', icon: '👻', type: 'utility', duration: 8, cooldown: 60, description: 'Removes movement impairing effects' },
      { name: 'Ancestral Guidance', icon: '🧙‍♂️', type: 'healing', duration: 10, cooldown: 120, description: 'Damage and healing heals 3 nearby allies' },
    ],
    ENHANCEMENT: [
      { name: 'Astral Shift', icon: '🌠', type: 'defensive', duration: 8, cooldown: 90, description: '40% damage reduction' },
      { name: 'Earth Elemental', icon: '🗿', type: 'defensive', duration: 60, cooldown: 300, description: 'Summons Earth Elemental tank' },
      { name: 'Feral Spirit', icon: '🐺', type: 'damage', duration: 15, cooldown: 120, description: 'Summons spirit wolves, increases damage' },
      { name: 'Spirit Walk', icon: '👻', type: 'utility', duration: 8, cooldown: 60, description: 'Removes movement impairing effects' },
      { name: 'Capacitor Totem', icon: '⚡', type: 'utility', duration: 'Instant', cooldown: 60, description: 'AoE stun after 2 seconds' },
      { name: 'Tremor Totem', icon: '📳', type: 'utility', duration: 10, cooldown: 60, description: 'Breaks fear, charm, sleep effects' },
      { name: 'Wind Shear', icon: '🌬️', type: 'utility', duration: 'Instant', cooldown: 12, description: 'Interrupts spellcasting' },
      { name: 'Ancestral Guidance', icon: '🧙‍♂️', type: 'healing', duration: 10, cooldown: 120, description: 'Damage and healing heals 3 nearby allies' },
    ]
  },
  MONK: {
    color: '#00FF96',
    icon: '🐼',
    MISTWEAVER: [
      { name: 'Revival', icon: '🌬️', type: 'healing', duration: 'Instant', cooldown: 180, description: 'Raid-wide heal and dispel' },
      { name: 'Life Cocoon', icon: '🥥', type: 'defensive', duration: 12, cooldown: 120, description: 'Shield and increased healing received' },
      { name: 'Chi-Ji', icon: '🐦', type: 'healing', duration: 25, cooldown: 180, description: 'Enhanced healing abilities' },
      { name: 'Yu\'lon', icon: '🐉', type: 'healing', duration: 25, cooldown: 180, description: 'Duplicates healing spells' },
      { name: 'Invoke Chi-Ji', icon: '🔥', type: 'healing', duration: 20, cooldown: 120, description: 'Increases healing and adds healing buff' },
      { name: 'Invoke Crane', icon: '🦩', type: 'utility', duration: 15, cooldown: 180, description: 'Heals based on damage dealt' },
      { name: 'Thunder Focus Tea', icon: '🍵', type: 'healing', duration: 30, cooldown: 30, description: 'Empowers next healing spell' },
      { name: 'Essence Font', icon: '💮', type: 'healing', duration: 'Channeled', cooldown: 12, description: 'Multi-target HoT' },
      { name: 'Renewing Mist', icon: '🍃', type: 'healing', duration: 20, cooldown: 9, description: 'HoT that can jump to new targets' },
      { name: 'Roll', icon: '🔄', type: 'utility', duration: 'Instant', cooldown: 20, description: 'Quickly roll a short distance' },
      { name: 'Transcendence', icon: '🧘', type: 'utility', duration: 'N/A', cooldown: 10, description: 'Swap places with spirit' },
    ],
    BREWMASTER: [
      { name: 'Fortifying Brew', icon: '🍺', type: 'defensive', duration: 15, cooldown: 420, description: 'Increases health and reduces damage' },
      { name: 'Zen Meditation', icon: '☯️', type: 'defensive', duration: 8, cooldown: 300, description: '90% spell damage reduction' },
      { name: 'Dampen Harm', icon: '🛡️', type: 'defensive', duration: 10, cooldown: 120, description: 'Reduces heavy hits by 50%' },
      { name: 'Purifying Brew', icon: '🧪', type: 'defensive', duration: 'Instant', cooldown: 20, description: 'Clears 50% of staggered damage' },
      { name: 'Celestial Brew', icon: '🌌', type: 'defensive', duration: 8, cooldown: 60, description: 'Creates absorption shield' },
      { name: 'Roll', icon: '🔄', type: 'utility', duration: 'Instant', cooldown: 20, description: 'Quickly roll a short distance' },
      { name: 'Transcendence', icon: '🧘', type: 'utility', duration: 'N/A', cooldown: 10, description: 'Swap places with spirit' },
      { name: 'Leg Sweep', icon: '🦵', type: 'utility', duration: 5, cooldown: 60, description: 'AoE stun' },
      { name: 'Bonedust Brew', icon: '🦴', type: 'utility', duration: 10, cooldown: 60, description: 'Increases healing and damage' },
    ],
    WINDWALKER: [
      { name: 'Touch of Karma', icon: '☯️', type: 'defensive', duration: 10, cooldown: 90, description: 'Redirects damage taken back to attacker' },
      { name: 'Diffuse Magic', icon: '✨', type: 'defensive', duration: 6, cooldown: 90, description: '60% magic damage reduction and debuff removal' },
      { name: 'Fortifying Brew', icon: '🍺', type: 'defensive', duration: 15, cooldown: 420, description: 'Increases health and reduces damage' },
      { name: 'Storm, Earth, and Fire', icon: '🌪️', type: 'damage', duration: 15, cooldown: 90, description: 'Splits into 3 forms, each dealing 45% damage' },
      { name: 'Serenity', icon: '☮️', type: 'damage', duration: 12, cooldown: 90, description: 'Increases damage by 20%, reduces cooldowns' },
      { name: 'Roll', icon: '🔄', type: 'utility', duration: 'Instant', cooldown: 20, description: 'Quickly roll a short distance' },
      { name: 'Transcendence', icon: '🧘', type: 'utility', duration: 'N/A', cooldown: 10, description: 'Swap places with spirit' },
      { name: 'Leg Sweep', icon: '🦵', type: 'utility', duration: 5, cooldown: 60, description: 'AoE stun' },
      { name: 'Flying Serpent Kick', icon: '🐉', type: 'utility', duration: 'Instant', cooldown: 25, description: 'Fly through the air, slow enemies on landing' },
    ]
  },
  WARRIOR: {
    color: '#C79C6E',
    icon: '⚔️',
    PROTECTION: [
      { name: 'Shield Wall', icon: '🛡️', type: 'defensive', duration: 8, cooldown: 240, description: '40% damage reduction' },
      { name: 'Last Stand', icon: '💪', type: 'defensive', duration: 15, cooldown: 180, description: 'Increases max health by 30%' },
      { name: 'Demoralizing Shout', icon: '📣', type: 'defensive', duration: 8, cooldown: 45, description: 'Reduces enemy damage by 20%' },
      { name: 'Rallying Cry', icon: '🏆', type: 'defensive', duration: 10, cooldown: 180, description: 'Increases raid health by 15%' },
      { name: 'Avatar', icon: '🗿', type: 'damage', duration: 20, cooldown: 90, description: 'Increases damage by 20%' },
      { name: 'Thunder Clap', icon: '⚡', type: 'damage', duration: 'Instant', cooldown: 6, description: 'AoE damage and slow' },
      { name: 'Shockwave', icon: '💥', type: 'utility', duration: 4, cooldown: 40, description: 'Cone AoE stun' },
      { name: 'Spell Reflection', icon: '🪞', type: 'defensive', duration: 5, cooldown: 25, description: 'Reflects next harmful spell' },
      { name: 'Intervene', icon: '🏃', type: 'utility', duration: 'Instant', cooldown: 30, description: 'Leap to ally, reducing their damage taken' },
    ],
    ARMS: [
      { name: 'Die by the Sword', icon: '🗡️', type: 'defensive', duration: 8, cooldown: 180, description: '30% damage reduction, 100% parry chance' },
      { name: 'Rallying Cry', icon: '🏆', type: 'defensive', duration: 10, cooldown: 180, description: 'Increases raid health by 15%' },
      { name: 'Defensive Stance', icon: '🛡️', type: 'defensive', duration: 'Toggle', cooldown: 6, description: '20% damage reduction, 10% less damage dealt' },
      { name: 'Bladestorm', icon: '🌪️', type: 'damage', duration: 6, cooldown: 90, description: 'Continuous AoE damage, immune to CC' },
      { name: 'Colossus Smash', icon: '💥', type: 'damage', duration: 10, cooldown: 45, description: 'Target takes 30% more damage' },
      { name: 'Spell Reflection', icon: '🪞', type: 'defensive', duration: 5, cooldown: 25, description: 'Reflects next harmful spell' },
      { name: 'Berserker Rage', icon: '😠', type: 'utility', duration: 6, cooldown: 60, description: 'Immune to fear, sap, and incapacitate effects' },
    ],
    FURY: [
      { name: 'Enraged Regeneration', icon: '🩸', type: 'healing', duration: 8, cooldown: 120, description: 'Self healing based on damage done' },
      { name: 'Rallying Cry', icon: '🏆', type: 'defensive', duration: 10, cooldown: 180, description: 'Increases raid health by 15%' },
      { name: 'Recklessness', icon: '🔥', type: 'damage', duration: 10, cooldown: 90, description: 'Increases critical strike chance by 30%' },
      { name: 'Spell Reflection', icon: '🪞', type: 'defensive', duration: 5, cooldown: 25, description: 'Reflects next harmful spell' },
      { name: 'Intimidating Shout', icon: '😱', type: 'utility', duration: 8, cooldown: 90, description: 'Causes enemies to flee' },
      { name: 'Berserker Rage', icon: '😠', type: 'utility', duration: 6, cooldown: 60, description: 'Immune to fear, sap, and incapacitate effects' },
    ]
  },
  WARLOCK: {
    color: '#9482C9',
    icon: '💀',
    AFFLICTION: [
      { name: 'Unending Resolve', icon: '🌑', type: 'defensive', duration: 8, cooldown: 180, description: '40% damage reduction' },
      { name: 'Dark Pact', icon: '🔮', type: 'defensive', duration: 'Instant', cooldown: 60, description: 'Sacrifices pet health for a shield' },
      { name: 'Demonic Gateway', icon: '🌀', type: 'utility', duration: 'Permanent', cooldown: 10, description: 'Creates a portal between two locations' },
      { name: 'Demonic Circle', icon: '⭕', type: 'utility', duration: 'Instant', cooldown: 30, description: 'Teleport to safe location' },
      { name: 'Soulstone', icon: '💎', type: 'utility', duration: 'Instant', cooldown: 600, description: 'Resurrects target upon death' },
      { name: 'Healthstone', icon: '💊', type: 'healing', duration: 'Instant', cooldown: 60, description: 'Conjures a healthstone that heals' },
      { name: 'Soul Rot', icon: '🦠', type: 'damage', duration: 8, cooldown: 60, description: 'Increases damage and leech on enemies' },
      { name: 'Summon Darkglare', icon: '👁️', type: 'damage', duration: 20, cooldown: 180, description: 'Summons Darkglare that extends DoTs' },
    ],
    DEMONOLOGY: [
      { name: 'Unending Resolve', icon: '🌑', type: 'defensive', duration: 8, cooldown: 180, description: '40% damage reduction' },
      { name: 'Demonic Circle', icon: '⭕', type: 'utility', duration: 'Instant', cooldown: 30, description: 'Teleport to safe location' },
      { name: 'Dark Pact', icon: '🔮', type: 'defensive', duration: 'Instant', cooldown: 60, description: 'Sacrifices pet health for a shield' },
      { name: 'Demonic Gateway', icon: '🌀', type: 'utility', duration: 'Permanent', cooldown: 10, description: 'Creates a portal between two locations' },
      { name: 'Soulstone', icon: '💎', type: 'utility', duration: 'Instant', cooldown: 600, description: 'Resurrects target upon death' },
      { name: 'Healthstone', icon: '💊', type: 'healing', duration: 'Instant', cooldown: 60, description: 'Conjures a healthstone that heals' },
      { name: 'Demonic Strength', icon: '💪', type: 'damage', duration: 'Instant', cooldown: 60, description: 'Empowers Felguard, causing AoE damage' },
      { name: 'Summon Demonic Tyrant', icon: '👹', type: 'damage', duration: 15, cooldown: 90, description: 'Summons Tyrant and empowers demons' },
    ],
    DESTRUCTION: [
      { name: 'Unending Resolve', icon: '🌑', type: 'defensive', duration: 8, cooldown: 180, description: '40% damage reduction' },
      { name: 'Nether Ward', icon: '🔮', type: 'defensive', duration: 3, cooldown: 45, description: 'Anti-magic shield' },
      { name: 'Demonic Gateway', icon: '🌀', type: 'utility', duration: 'Permanent', cooldown: 10, description: 'Creates a portal between two locations' },
      { name: 'Demonic Circle', icon: '⭕', type: 'utility', duration: 'Instant', cooldown: 30, description: 'Teleport to safe location' },
      { name: 'Soulstone', icon: '💎', type: 'utility', duration: 'Instant', cooldown: 600, description: 'Resurrects target upon death' },
      { name: 'Healthstone', icon: '💊', type: 'healing', duration: 'Instant', cooldown: 60, description: 'Conjures a healthstone that heals' },
      { name: 'Havoc', icon: '🎯', type: 'damage', duration: 10, cooldown: 30, description: 'Duplicates spells on second target' },
      { name: 'Summon Infernal', icon: '🔥', type: 'damage', duration: 30, cooldown: 180, description: 'Summons an Infernal that stuns and deals damage' },
    ]
  },
  MAGE: {
    color: '#69CCF0',
    icon: '🧙',
    ARCANE: [
      { name: 'Ice Block', icon: '🧊', type: 'defensive', duration: 10, cooldown: 240, description: 'Complete immunity to damage' },
      { name: 'Greater Invisibility', icon: '👻', type: 'defensive', duration: 12, cooldown: 120, description: 'Reduces damage taken by 60%' },
      { name: 'Mirror Image', icon: '🪞', type: 'defensive', duration: 40, cooldown: 120, description: 'Summons copies to distract enemies' },
      { name: 'Alter Time', icon: '⏳', type: 'utility', duration: 10, cooldown: 60, description: 'Return to prior location and health' },
      { name: 'Arcane Power', icon: '⚡', type: 'damage', duration: 10, cooldown: 90, description: 'Increases spell damage by 30%' },
      { name: 'Presence of Mind', icon: '🌟', type: 'utility', duration: 'Instant', cooldown: 60, description: 'Next Arcane Blast is instant' },
      { name: 'Prismatic Barrier', icon: '🌈', type: 'defensive', duration: 60, cooldown: 25, description: 'Reduces magic damage taken by 40%' },
      { name: 'Frost Nova', icon: '❄️', type: 'utility', duration: 8, cooldown: 30, description: 'Freezes all enemies within 8 yards' },
      { name: 'Blink', icon: '⚡', type: 'utility', duration: 'Instant', cooldown: 15, description: 'Teleport 20 yards forward' },
    ],
    FIRE: [
      { name: 'Ice Block', icon: '🧊', type: 'defensive', duration: 10, cooldown: 240, description: 'Complete immunity to damage' },
      { name: 'Blazing Barrier', icon: '🔥', type: 'defensive', duration: 60, cooldown: 25, description: 'Absorbs damage and burns attackers' },
      { name: 'Mirror Image', icon: '🪞', type: 'defensive', duration: 40, cooldown: 120, description: 'Summons copies to distract enemies' },
      { name: 'Combustion', icon: '🔥', type: 'damage', duration: 10, cooldown: 120, description: '100% critical strike chance' },
      { name: 'Alter Time', icon: '⏳', type: 'utility', duration: 10, cooldown: 60, description: 'Return to prior location and health' },
      { name: 'Dragon\'s Breath', icon: '🐉', type: 'utility', duration: 4, cooldown: 45, description: 'Disorients all enemies in front of you' },
      { name: 'Frost Nova', icon: '❄️', type: 'utility', duration: 8, cooldown: 30, description: 'Freezes all enemies within 8 yards' },
      { name: 'Blink', icon: '⚡', type: 'utility', duration: 'Instant', cooldown: 15, description: 'Teleport 20 yards forward' },
    ],
    FROST: [
      { name: 'Ice Block', icon: '🧊', type: 'defensive', duration: 10, cooldown: 240, description: 'Complete immunity to damage' },
      { name: 'Cold Snap', icon: '❄️', type: 'utility', duration: 'Instant', cooldown: 300, description: 'Resets all Frost cooldowns' },
      { name: 'Ice Barrier', icon: '🧊', type: 'defensive', duration: 60, cooldown: 25, description: 'Absorbs damage' },
      { name: 'Mirror Image', icon: '🪞', type: 'defensive', duration: 40, cooldown: 120, description: 'Summons copies to distract enemies' },
      { name: 'Icy Veins', icon: '💙', type: 'damage', duration: 20, cooldown: 180, description: 'Increases haste by 30%' },
      { name: 'Frost Nova', icon: '❄️', type: 'utility', duration: 8, cooldown: 30, description: 'Freezes all enemies within 8 yards' },
      { name: 'Ice Floes', icon: '🌊', type: 'utility', duration: 15, cooldown: 45, description: 'Cast while moving' },
      { name: 'Blink', icon: '⚡', type: 'utility', duration: 'Instant', cooldown: 15, description: 'Teleport 20 yards forward' },
      { name: 'Alter Time', icon: '⏳', type: 'utility', duration: 10, cooldown: 60, description: 'Return to prior location and health' },
    ]
  },
  HUNTER: {
    color: '#ABD473',
    icon: '🏹',
    BEAST_MASTERY: [
      { name: 'Aspect of the Turtle', icon: '🐢', type: 'defensive', duration: 8, cooldown: 180, description: 'Complete damage immunity, cannot attack' },
      { name: 'Exhilaration', icon: '💚', type: 'healing', duration: 'Instant', cooldown: 120, description: 'Heals hunter and pet for 30%' },
      { name: 'Survival of the Fittest', icon: '💪', type: 'defensive', duration: 6, cooldown: 180, description: '20% damage reduction' },
      { name: 'Aspect of the Wild', icon: '🦌', type: 'damage', duration: 20, cooldown: 120, description: 'Increases focus regeneration and damage' },
      { name: 'Bestial Wrath', icon: '😡', type: 'damage', duration: 15, cooldown: 90, description: 'Increases pet damage by 30%, immune to CC' },
      { name: 'Intimidation', icon: '😱', type: 'utility', duration: 3, cooldown: 60, description: 'Your pet stuns the target' },
      { name: 'Binding Shot', icon: '🎯', type: 'utility', duration: 'Instant', cooldown: 45, description: 'Tethers enemies, stunning if they move' },
      { name: 'Concussive Shot', icon: '💫', type: 'utility', duration: 6, cooldown: 5, description: 'Slows the target by 50%' },
      { name: 'Aspect of the Cheetah', icon: '🐆', type: 'utility', duration: 3, cooldown: 180, description: 'Increases movement speed by 90%' },
    ],
    MARKSMANSHIP: [
      { name: 'Aspect of the Turtle', icon: '🐢', type: 'defensive', duration: 8, cooldown: 180, description: 'Complete damage immunity, cannot attack' },
      { name: 'Exhilaration', icon: '💚', type: 'healing', duration: 'Instant', cooldown: 120, description: 'Heals hunter for 30%' },
      { name: 'Camouflage', icon: '🌿', type: 'utility', duration: 60, cooldown: 60, description: 'Become invisible and increase stealth' },
      { name: 'Binding Shot', icon: '🎯', type: 'utility', duration: 'Instant', cooldown: 45, description: 'Tethers enemies, stunning if they move' },
      { name: 'Trueshot', icon: '🎯', type: 'damage', duration: 15, cooldown: 120, description: 'Increases focus regeneration and critical strike chance' },
      { name: 'Bursting Shot', icon: '💥', type: 'utility', duration: 'Instant', cooldown: 24, description: 'Knocks back enemies and disorients them' },
      { name: 'Volley', icon: '🏹', type: 'damage', duration: 6, cooldown: 45, description: 'Continuous AoE damage' },
      { name: 'Aspect of the Cheetah', icon: '🐆', type: 'utility', duration: 3, cooldown: 180, description: 'Increases movement speed by 90%' },
    ],
    SURVIVAL: [
      { name: 'Aspect of the Turtle', icon: '🐢', type: 'defensive', duration: 8, cooldown: 180, description: 'Complete damage immunity, cannot attack' },
      { name: 'Exhilaration', icon: '💚', type: 'healing', duration: 'Instant', cooldown: 120, description: 'Heals hunter for 30%' },
      { name: 'Coordinated Assault', icon: '👥', type: 'damage', duration: 20, cooldown: 120, description: 'Increases damage by 20%, shares pet abilities' },
      { name: 'Aspect of the Eagle', icon: '🦅', type: 'damage', duration: 15, cooldown: 90, description: 'Increases Raptor Strike and Mongoose Bite range' },
      { name: 'Muzzle', icon: '🤐', type: 'utility', duration: 'Instant', cooldown: 15, description: 'Interrupts spellcasting' },
      { name: 'Harpoon', icon: '🔱', type: 'utility', duration: 'Instant', cooldown: 30, description: 'Pull yourself to an enemy, rooting them' },
      { name: 'Aspect of the Cheetah', icon: '🐆', type: 'utility', duration: 3, cooldown: 180, description: 'Increases movement speed by 90%' },
      { name: 'Wing Clip', icon: '🦅', type: 'utility', duration: 15, cooldown: 0, description: 'Slows the target by 50%' },
    ]
  },
  ROGUE: {
    color: '#FFF569',
    icon: '🗡️',
    ASSASSINATION: [
      { name: 'Cloak of Shadows', icon: '🌑', type: 'defensive', duration: 5, cooldown: 120, description: '100% magic damage reduction' },
      { name: 'Evasion', icon: '🤸', type: 'defensive', duration: 10, cooldown: 120, description: '100% dodge chance' },
      { name: 'Feint', icon: '👻', type: 'defensive', duration: 5, cooldown: 15, description: '40% AoE damage reduction' },
      { name: 'Vendetta', icon: '🩸', type: 'damage', duration: 20, cooldown: 120, description: '30% increased damage on target' },
      { name: 'Vanish', icon: '🌫️', type: 'utility', duration: 'Instant', cooldown: 120, description: 'Enter stealth, dropping threat' },
      { name: 'Crimson Vial', icon: '🧪', type: 'healing', duration: 4, cooldown: 30, description: 'Heals for 20% of max health over 4 seconds' },
      { name: 'Shroud of Concealment', icon: '👥', type: 'utility', duration: 15, cooldown: 360, description: 'Group stealth' },
      { name: 'Kidney Shot', icon: '💥', type: 'utility', duration: '1-6', cooldown: 20, description: 'Stuns target based on combo points' },
      { name: 'Sprint', icon: '🏃', type: 'utility', duration: 8, cooldown: 60, description: 'Increases movement speed by 70%' },
    ],
    OUTLAW: [
      { name: 'Cloak of Shadows', icon: '🌑', type: 'defensive', duration: 5, cooldown: 120, description: '100% magic damage reduction' },
      { name: 'Riposte', icon: '⚔️', type: 'defensive', duration: 10, cooldown: 120, description: '100% parry chance' },
      { name: 'Crimson Vial', icon: '🩸', type: 'healing', duration: 4, cooldown: 30, description: 'Self heal over time' },
      { name: 'Adrenaline Rush', icon: '⚡', type: 'damage', duration: 20, cooldown: 180, description: 'Increases energy regeneration and attack speed' },
      { name: 'Blade Rush', icon: '🗡️', type: 'damage', duration: 'Instant', cooldown: 45, description: 'AoE damage and energy generation' },
      { name: 'Killing Spree', icon: '💀', type: 'damage', duration: 2, cooldown: 120, description: 'Teleport to and attack multiple targets' },
      { name: 'Vanish', icon: '🌫️', type: 'utility', duration: 'Instant', cooldown: 120, description: 'Enter stealth, dropping threat' },
      { name: 'Grappling Hook', icon: '🪝', type: 'utility', duration: 'Instant', cooldown: 60, description: 'Pull yourself to a location' },
      { name: 'Between the Eyes', icon: '👁️', type: 'utility', duration: '1-6', cooldown: 30, description: 'Stuns target based on combo points' },
      { name: 'Sprint', icon: '🏃', type: 'utility', duration: 8, cooldown: 60, description: 'Increases movement speed by 70%' },
    ],
    SUBTLETY: [
      { name: 'Cloak of Shadows', icon: '🌑', type: 'defensive', duration: 5, cooldown: 120, description: '100% magic damage reduction' },
      { name: 'Evasion', icon: '🤸', type: 'defensive', duration: 10, cooldown: 120, description: '100% dodge chance' },
      { name: 'Shadow Dance', icon: '💃', type: 'utility', duration: 8, cooldown: 60, description: 'Access to stealth abilities' },
      { name: 'Symbols of Death', icon: '☠️', type: 'damage', duration: 10, cooldown: 30, description: 'Increases damage and critical strike chance' },
      { name: 'Shadow Blades', icon: '🌒', type: 'damage', duration: 20, cooldown: 180, description: 'Auto-attacks generate combo points' },
      { name: 'Secret Technique', icon: '👤', type: 'damage', duration: 'Instant', cooldown: 45, description: 'Deals high single target and cleave damage' },
      { name: 'Vanish', icon: '🌫️', type: 'utility', duration: 'Instant', cooldown: 120, description: 'Enter stealth, dropping threat' },
      { name: 'Shroud of Concealment', icon: '👥', type: 'utility', duration: 15, cooldown: 360, description: 'Group stealth' },
      { name: 'Shadowstep', icon: '👤', type: 'utility', duration: 'Instant', cooldown: 30, description: 'Teleport behind target' },
      { name: 'Sprint', icon: '🏃', type: 'utility', duration: 8, cooldown: 60, description: 'Increases movement speed by 70%' },
    ]
  },
  DEATH_KNIGHT: {
    color: '#C41F3B',
    icon: '💀',
    BLOOD: [
      { name: 'Vampiric Blood', icon: '🩸', type: 'defensive', duration: 10, cooldown: 90, description: 'Increases max health by 30% and healing received by 30%' },
      { name: 'Dancing Rune Weapon', icon: '🗡️', type: 'defensive', duration: 8, cooldown: 120, description: 'Duplicate that mimics abilities and increases parry chance' },
      { name: 'Anti-Magic Shell', icon: '🛡️', type: 'defensive', duration: 5, cooldown: 60, description: 'Absorbs 100% of magic damage' },
      { name: 'Icebound Fortitude', icon: '❄️', type: 'defensive', duration: 8, cooldown: 180, description: '30% damage reduction, cannot be stunned' },
      { name: 'Anti-Magic Zone', icon: '🌀', type: 'defensive', duration: 8, cooldown: 120, description: 'Reduces magic damage for all allies by 20%' },
      { name: 'Tombstone', icon: '⚰️', type: 'defensive', duration: 8, cooldown: 60, description: 'Consumes Bone Shield charges for an absorb shield' },
      { name: 'Raise Ally', icon: '👻', type: 'utility', duration: 'Instant', cooldown: 600, description: 'Resurrects an ally as a ghoul temporarily' },
      { name: 'Gorefiend\'s Grasp', icon: '🪝', type: 'utility', duration: 'Instant', cooldown: 120, description: 'Pulls all enemies to a target' },
      { name: 'Death Grip', icon: '✊', type: 'utility', duration: 'Instant', cooldown: 25, description: 'Pulls an enemy to you and taunts' },
    ],
    FROST: [
      { name: 'Anti-Magic Shell', icon: '🛡️', type: 'defensive', duration: 5, cooldown: 60, description: 'Absorbs 100% of magic damage' },
      { name: 'Icebound Fortitude', icon: '❄️', type: 'defensive', duration: 8, cooldown: 180, description: '30% damage reduction, cannot be stunned' },
      { name: 'Anti-Magic Zone', icon: '🌀', type: 'defensive', duration: 8, cooldown: 120, description: 'Reduces magic damage for all allies by 20%' },
      { name: 'Raise Ally', icon: '👻', type: 'utility', duration: 'Instant', cooldown: 600, description: 'Resurrects an ally as a ghoul temporarily' },
      { name: 'Pillar of Frost', icon: '🧊', type: 'damage', duration: 12, cooldown: 60, description: 'Increases Strength by 20%' },
      { name: 'Empower Rune Weapon', icon: '⚔️', type: 'damage', duration: 20, cooldown: 105, description: 'Empowers weapons, refills runes' },
      { name: 'Breath of Sindragosa', icon: '🐉', type: 'damage', duration: 'Variable', cooldown: 120, description: 'Channeled cone AoE damage' },
      { name: 'Death Grip', icon: '✊', type: 'utility', duration: 'Instant', cooldown: 25, description: 'Pulls an enemy to you' },
      { name: 'Chains of Ice', icon: '❄️', type: 'utility', duration: 8, cooldown: 0, description: 'Slows target by 70%' },
    ],
    UNHOLY: [
      { name: 'Anti-Magic Shell', icon: '🛡️', type: 'defensive', duration: 5, cooldown: 60, description: 'Absorbs 100% of magic damage' },
      { name: 'Icebound Fortitude', icon: '❄️', type: 'defensive', duration: 8, cooldown: 180, description: '30% damage reduction, cannot be stunned' },
      { name: 'Lichborne', icon: '👻', type: 'defensive', duration: 10, cooldown: 120, description: 'Transforms into undead, immune to charm, fear, sleep' },
      { name: 'Anti-Magic Zone', icon: '🌀', type: 'defensive', duration: 8, cooldown: 120, description: 'Reduces magic damage for all allies by 20%' },
      { name: 'Raise Ally', icon: '👻', type: 'utility', duration: 'Instant', cooldown: 600, description: 'Resurrects an ally as a ghoul temporarily' },
      { name: 'Army of the Dead', icon: '⚰️', type: 'damage', duration: 30, cooldown: 480, description: 'Summons ghouls to fight for you' },
      { name: 'Summon Gargoyle', icon: '🗿', type: 'damage', duration: 25, cooldown: 180, description: 'Summons gargoyle to attack your target' },
      { name: 'Dark Transformation', icon: '🧟', type: 'damage', duration: 15, cooldown: 60, description: 'Empowers your permanent ghoul' },
      { name: 'Death Grip', icon: '✊', type: 'utility', duration: 'Instant', cooldown: 25, description: 'Pulls an enemy to you' },
      { name: 'Unholy Blight', icon: '☣️', type: 'damage', duration: 6, cooldown: 45, description: 'AoE disease damage' },
      { name: 'Apocalypse', icon: '☠️', type: 'damage', duration: 'Instant', cooldown: 90, description: 'Bursts Festering Wounds, summons minions' }
    ]
  },
  DEMON_HUNTER: {
    color: '#A330C9',
    icon: '👿',
    HAVOC: [
      { name: 'Blur', icon: '💨', type: 'defensive', duration: 10, cooldown: 60, description: '20% dodge chance, 50% damage reduction' },
      { name: 'Netherwalk', icon: '🌌', type: 'defensive', duration: 6, cooldown: 180, description: '100% damage reduction, cannot attack' },
      { name: 'Darkness', icon: '🌑', type: 'defensive', duration: 8, cooldown: 300, description: 'All allies have 20% chance to avoid damage' },
      { name: 'Metamorphosis', icon: '😈', type: 'damage', duration: 30, cooldown: 240, description: 'Transform into demon, increased damage' },
      { name: 'Eye Beam', icon: '👁️', type: 'damage', duration: '2-3', cooldown: 40, description: 'Channel high damage in front of you' },
      { name: 'Fel Rush', icon: '💨', type: 'utility', duration: 'Instant', cooldown: 10, description: 'Dash forward, dealing damage' },
      { name: 'Vengeful Retreat', icon: '↩️', type: 'utility', duration: 'Instant', cooldown: 25, description: 'Leap backwards and slow enemies' },
      { name: 'Chaos Nova', icon: '💫', type: 'utility', duration: 2, cooldown: 60, description: 'AoE stun around you' },
      { name: 'Disruption', icon: '🤐', type: 'utility', duration: 'Instant', cooldown: 15, description: 'Interrupt and 3 sec silence' },
      { name: 'Imprison', icon: '🔒', type: 'utility', duration: 4, cooldown: 45, description: 'Incapacitate a demon or beast' }
    ],
    VENGEANCE: [
      { name: 'Metamorphosis', icon: '😈', type: 'defensive', duration: 15, cooldown: 180, description: '30% increased armor, 50% healing increase' },
      { name: 'Fiery Brand', icon: '🔥', type: 'defensive', duration: 8, cooldown: 60, description: '40% damage reduction from target' },
      { name: 'Demon Spikes', icon: '🛡️', type: 'defensive', duration: 6, cooldown: 20, description: 'Increases armor and parry chance' },
      { name: 'Soul Barrier', icon: '🌀', type: 'defensive', duration: 12, cooldown: 30, description: 'Creates an absorb shield based on souls' },
      { name: 'Fel Devastation', icon: '🔥', type: 'damage', duration: 2, cooldown: 60, description: 'Channel dealing damage and healing you' },
      { name: 'Sigil of Chains', icon: '⛓️', type: 'utility', duration: 'Instant', cooldown: 90, description: 'Pulls and slows enemies' },
      { name: 'Sigil of Silence', icon: '🤫', type: 'utility', duration: 6, cooldown: 60, description: 'AoE silence' },
      { name: 'Sigil of Misery', icon: '😱', type: 'utility', duration: 22, cooldown: 90, description: 'AoE fear' },
      { name: 'Infernal Strike', icon: '💥', type: 'utility', duration: 'Instant', cooldown: 20, description: 'Leap and deal damage at landing location' },
      { name: 'Throw Glaive', icon: '🔄', type: 'utility', duration: 'Instant', cooldown: 3, description: 'Ranged attack that slows' }
    ]
  },
  EVOKER: {
    color: '#33937F',
    icon: '🐉',
    DEVASTATION: [
      { name: 'Obsidian Scales', icon: '🐲', type: 'defensive', duration: 12, cooldown: 90, description: '30% damage reduction, immune to DoTs' },
      { name: 'Renewing Blaze', icon: '🔥', type: 'healing', duration: 8, cooldown: 60, description: 'Self heal over time, DR at low health' },
      { name: 'Time Dilation', icon: '⏱️', type: 'damage', duration: 'Instant', cooldown: 120, description: 'Reset cooldowns of core abilities' },
      { name: 'Eternity Surge', icon: '💥', type: 'damage', duration: 'Channeled', cooldown: 30, description: 'Channel powerful breath attack' },
      { name: 'Dragonrage', icon: '🔥', type: 'damage', duration: 18, cooldown: 120, description: 'Empowers abilities, increases damage' },
      { name: 'Fire Breath', icon: '🔥', type: 'damage', duration: 'Channeled', cooldown: 20, description: 'Cone breath attack with empower levels' },
      { name: 'Deep Breath', icon: '🐉', type: 'damage', duration: 'Instant', cooldown: 120, description: 'Fly up and breathe fire on large area' },
      { name: 'Hover', icon: '🦋', type: 'utility', duration: 'Instant', cooldown: 35, description: 'Hover over the ground, avoiding ground effects' },
      { name: 'Emerald Blossom', icon: '🌱', type: 'healing', duration: 'Instant', cooldown: 15, description: 'Small group heal' },
      { name: 'Sleep Walk', icon: '😴', type: 'utility', duration: 20, cooldown: 60, description: 'Put target to sleep, wake on damage' }
    ],
    PRESERVATION: [
      { name: 'Reversion', icon: '🧬', type: 'healing', duration: 8, cooldown: 120, description: 'Duplicates healing on low health targets' },
      { name: 'Dream Flight', icon: '✨', type: 'healing', duration: 15, cooldown: 120, description: 'Channel raid healing, plus HoT' },
      { name: 'Time Dilation', icon: '⏱️', type: 'healing', duration: 'Instant', cooldown: 60, description: 'Extends HoTs and reduces their interval' },
      { name: 'Emerald Communion', icon: '💚', type: 'healing', duration: 5, cooldown: 180, description: 'Massive healing channel, damage immune' },
      { name: 'Stasis', icon: '🔮', type: 'defensive', duration: 4, cooldown: 90, description: 'Prevent target from dying, then heal 30%' },
      { name: 'Obsidian Scales', icon: '🐲', type: 'defensive', duration: 12, cooldown: 90, description: '30% damage reduction, immune to DoTs' },
      { name: 'Dream Breath', icon: '💫', type: 'healing', duration: 'Channel', cooldown: 15, description: 'Cone healing with empower levels' },
      { name: 'Verdant Embrace', icon: '🌿', type: 'healing', duration: 30, cooldown: 90, description: 'HoT that jumps to injured allies' },
      { name: 'Spiritbloom', icon: '🌺', type: 'healing', duration: 'Channel', cooldown: 30, description: 'Multi-target healing with empower levels' },
      { name: 'Emerald Blossom', icon: '🌱', type: 'healing', duration: 'Instant', cooldown: 15, description: 'Small group heal' },
      { name: 'Hover', icon: '🦋', type: 'utility', duration: 'Instant', cooldown: 35, description: 'Hover over the ground, avoiding ground effects' },
      { name: 'Sleep Walk', icon: '😴', type: 'utility', duration: 20, cooldown: 60, description: 'Put target to sleep, wake on damage' }
    ],
    AUGMENTATION: [
      { name: 'Chrono Ward', icon: '⏳', type: 'defensive', duration: 12, cooldown: 120, description: 'Blocks next 3 harmful effects' },
      { name: 'Obsidian Scales', icon: '🐲', type: 'defensive', duration: 12, cooldown: 90, description: '30% damage reduction, immune to DoTs' },
      { name: 'Renewing Blaze', icon: '🔥', type: 'healing', duration: 8, cooldown: 60, description: 'Self heal over time, DR at low health' },
      { name: 'Blistering Scales', icon: '🧪', type: 'utility', duration: 30, cooldown: 120, description: 'Increases ally haste (group buff)' },
      { name: 'Breath of Eons', icon: '🌠', type: 'damage', duration: 'Channel', cooldown: 120, description: 'Powerful AoE breath with empower levels' },
      { name: 'Shifting Power', icon: '⚡', type: 'utility', duration: 4, cooldown: 60, description: 'Channel to reduce cooldowns of other abilities' },
      { name: 'Time Spiral', icon: '🌀', type: 'utility', duration: 'Instant', cooldown: 120, description: 'Reset cooldowns for all party members' },
      { name: 'Ebon Might', icon: '⚫', type: 'utility', duration: 10, cooldown: 30, description: 'Empower allies with bonus stats' },
      { name: 'Hover', icon: '🦋', type: 'utility', duration: 'Instant', cooldown: 35, description: 'Hover over the ground, avoiding ground effects' },
      { name: 'Emerald Communion', icon: '💚', type: 'healing', duration: 5, cooldown: 180, description: 'Massive healing channel, damage immune' },
      { name: 'Sleep Walk', icon: '😴', type: 'utility', duration: 20, cooldown: 60, description: 'Put target to sleep, wake on damage' }
    ]
  }
};

// Eventos de boss predeterminados
const DEFAULT_BOSS_EVENTS = [
  { time: 0, name: 'Pull', description: 'The boss is pulled' },
  { time: 30, name: 'AoE Damage 1', description: 'First raid-wide damage' },
  { time: 90, name: 'Major Mechanic', description: 'High damage phase' },
  { time: 150, name: 'AoE Damage 2', description: 'Second raid-wide damage' },
  { time: 210, name: 'Final Phase', description: 'Boss enters final phase' },
  { time: 270, name: 'Enrage', description: 'Boss enrages, increased damage' },
];
// Función de ayuda para formatear tiempo como MM:SS
const formatTime = (seconds) => {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

export { WOW_CLASSES, DEFAULT_BOSS_EVENTS, formatTime };